name: server-starter
services:
  server:
    build: .
    container_name: server
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  db:
    image: postgres:alpine3.22
    container_name: pg-db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata-starter:/var/lib/postgresql/data

  mongo:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - mongodata-starter:/data/db

volumes:
  pgdata-starter:
  mongodata-starter:
